name: Auto Tagging

on:
  release:
    types: [published]

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

    - name: Fetch all tags
      run: git fetch --tags

    - name: Create new tag
      run: |
        # Fetch the latest tag
        latestTag=$(git describe --tags `git rev-list --tags --max-count=1`)
        # Increment the tag
        newTag=$(echo "$latestTag" | awk -F. '{$NF = $NF + 1;} 1' OFS=.)
        echo "Creating new tag: $newTag"
        # Create the new tag
        git tag $newTag
        git push origin $newTag
