name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

    - name: Fetch all tags
      run: git fetch --tags

    - name: Create new tag
      run: |
        # Fetch the latest tag
        latestTag=$(git describe --tags `git rev-list --tags --max-count=1`)
        # Increment the tag
        newTag=$(echo "$latestTag" | awk -F. '{$NF = $NF + 1;} 1' OFS=.)
        echo "Creating new tag: $newTag"
        # Create the new tag
        git tag $newTag
        git push origin $newTag
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Build package
      run: python -m build
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
